

CREATE DATABASE BDBEAUTYSALON

USE BDBEAUTYSALON

GO
-- tabla inventario

    CREATE TABLE INVENTARIO (
    [ID_PRODUCTO] [INT] IDENTITY(1,2) NOT NULL PRIMARY KEY,
	[PROVEEDOR] [VARCHAR](50) NOT NULL,
	[PRODUCTO] [VARCHAR](100) NOT NULL,  
	[PRECIO_VENTA] [FLOAT] NOT NULL,
	[PRECIO_COSTO] [FLOAT] NULL,
	[COMISION][FLOAT]NULL,
	[CANTIDAD] [INT] NOT NULL,
	[UBICACION] [VARCHAR] (50) NOT NULL,	
	[USUARIO] [VARCHAR] (40) NOT NULL,
	[FECHA_INGRESO] [DATETIME] NOT NULL
	
)

--TABLA USUARIOS

    CREATE TABLE USUARIOS (
	[ID_USUARIO] [INT] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[NOMBRE] [VARCHAR](25) NOT NULL,
	[APELLIDO] [VARCHAR](50) NOT NULL,
	[NOMBRE_DE_USUARIO] [VARCHAR](50) NOT NULL,
	[CONTRASENA] [VARCHAR](50) NOT NULL,
	[CARGO] [VARCHAR] (15) NOT NULL,
	[PRIVILEGIOS] [VARCHAR] (15) NOT NULL
	
)
insert into USUARIOS(NOMBRE,APELLIDO,NOMBRE_DE_USUARIO,CONTRASENA,CARGO,PRIVILEGIOS) VALUES ('usuario','usuario','usuario','1234','administrador','Administrador')

--TABLA PROVEEDORES

CREATE TABLE PROVEEDORES (
[ID_PROVEEDOR] [INT] IDENTITY (1,1) NOT NULL PRIMARY KEY,
[NOMBRE] [VARCHAR] (50) NOT NULL,
[RNC] [VARCHAR](11)  NULL,
[TELEFONO] [VARCHAR] (13) NOT NULL,
[WHATSAPP] [VARCHAR] (13)  NULL,
[DIRECCION] [VARCHAR] (35) NULL,
[EMAIL] [VARCHAR] (35) NULL,
[SUMINISTRO] [VARCHAR](50) NULL

)

--TABLA CLIENTES

    CREATE TABLE CLIENTES (
	[CODIGO] [INT] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[NOMBRE] [VARCHAR](25) NOT NULL,
	[APELLIDO] [VARCHAR](25) NOT NULL,
	[CELULAR] [VARCHAR](13)  NULL,
	[CUMPLEAÑOS] [DATETIME] NULL,
	[CITA] [DATETIME] NULL,
	[ANOTACIONES] [VARCHAR] (250)NULL,
	[VISITAS][INT] NULL ,
	[CREDITO][FLOAT]NULL,
	[FECHA_ULTIMO_PAGO][DATETIME] NULL
	)

CREATE TABLE HORARIO(
[ID][INT] IDENTITY(1,1)NOT NULL PRIMARY KEY,
[HORA_ENTRADA][DATETIME] NULL,
[HORA_SALIDA][DATETIME] NULL,
[FECHA][DATETIME]NOT NULL
)

--Tabla datos de empleado

CREATE TABLE DATOS_EMPLEADOS(
[CODIGO][INT]IDENTITY(1,1)NOT NULL PRIMARY KEY,
[NOMBRE][VARCHAR](25)NOT NULL,
[CEDULA][VARCHAR](13)NOT NULL,
[DIRECCION][VARCHAR](50)NOT NULL,
[SUELDO][FLOAT] NOT NULL,
[CELULAR][VARCHAR](15) NOT NULL,
[CEL_PARIENTE_1][VARCHAR](15) NULL,
[CEL_PARIENTE_2][VARCHAR](15) NULL,
[FECHA_INGRESO] [DATETIME] NOT NULL,
[FOTO][IMAGE] NULL
)

CREATE TABLE EMPRESA(
[ID_EMPRESA][INT] IDENTITY (1,1)NOT NULL PRIMARY KEY,
[NOMBRE_EMPRESA][VARCHAR](50)NOT NULL,
[RNC][VARCHAR](13) NOT NULL,
[DIRECCION][VARCHAR](50) NOT NULL,
[TELEFONO][VARCHAR](15) NULL,
[CELULAR][VARCHAR](15)NOT NULL,
[ADMINISTRADOR][VARCHAR](50)NOT NULL
)
CREATE TABLE REPORTES_VENTAS(
[ID_VENTA][INT] IDENTITY (1,1)NOT NULL PRIMARY KEY,
[SERVICIO_VENTA][VARCHAR](50)NOT NULL,
[VALOR][FLOAT]NOT NULL,
[REALIZADO_POR][VARCHAR](50)NULL,
[COMISIONES][FLOAT]NULL,
[FECHA][DATETIME]NOT NULL,
[GANANCIA][FLOAT] NULL ,
[TIPO_DE_PAGO][VARCHAR](20) NOT NULL,
[TIPO_DE_VENTA][VARCHAR](15) NULL,
[FIN_DIA][VARCHAR](10)NULL,
[PAGO_COMISION][VARCHAR](5)NULL
)


CREATE TABLE CUADRE_MENSUAL(
[ID][INT]IDENTITY(1,1)NOT NULL PRIMARY KEY,
[VALOR_RECAUDACION][FLOAT] NULL,
[COMISIONES_DEL_DIA][FLOAT] NULL,
[GANANCIA_DEL_DIA][FLOAT]NULL,
[VENTAS_EFECTIVO][FLOAT]NULL,
[VENTAS_CREDITO][FLOAT]NULL,
[VENTAS_TARJETA][FLOAT]NULL,
[GASTO_DIARIO][FLOAT]NULL,
[FECHA][DATETIME]NULL,
[USUARIO][VARCHAR](15)NULL

)

CREATE TABLE SERVICIOS(
[ID_SERVICIO][INT] IDENTITY (2,2) NOT NULL PRIMARY KEY,
[SERVICIO][VARCHAR](100)NOT NULL,
[PRECIO][FLOAT]NOT NULL,
[PRECIO_COMISION][FLOAT]NULL,
[COMISION][FLOAT] NULL,
[BENEFICIO_EMPLEADO][FLOAT] NULL,
[USUARIO][VARCHAR](50)NOT NULL
)
-- SE AGREGO TABLA GASTOS
CREATE TABLE GASTOS(
[ID][INT]IDENTITY (1,1)NOT NULL PRIMARY KEY,
[GASTO][FLOAT]NOT NULL,
[CONCEPTO][VARCHAR](50)NOT NULL,
[NOTAS][VARCHAR](100) NULL,
[FECHA][DATETIME]NOT NULL,
[FIN_DIA][VARCHAR](10)NULL

)
-- cambios
select * from HORARIO 
drop table horario

drop table RECORDATORIOS
alter table reportes_ventas add PAGO_COMISION VARCHAR (5) NULL
alter table clientes add FECHA_ULTIMO_PAGO DATETIME NULL

-- agregar tabla horario
-- mas cambios PARA REALIZAR
alter table inventario add COMISION FLOAT NULL
alter table GASTOS add FIN_DIA VARCHAR (10) NULL
alter table CUADRE_MENSUAL add GASTO_DIARIO FLOAT NULL



